/**
 * tokens.js — THE single source of design values for this app.
 *
 * CommonJS on purpose: tailwind.config.js must `require()` it, and the TypeScript
 * app imports it too (tsconfig has allowJs + esModuleInterop). One file, two
 * consumers, no duplicated value — DS-019.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * WHY THESE ARE PINNED BY HAND RATHER THAN GENERATED
 *
 * `theme.ts` at the app root IS generated by token-gen from DESIGN-CONTRACT.md,
 * and it is kept — but it CANNOT express this brand, which was proven by
 * measurement rather than assumed:
 *
 *   generated light primary  #806700  L=0.523 C=0.107   a muddy dark gold
 *   ratified  ember-400      #FACC15  L=0.861 C=0.173   the bulb
 *
 * The generator solves foregrounds for contrast from a seed. On a white ground
 * ember measures ~1.7:1, so the solver walked the PRIMARY down until white text
 * passed — satisfying WCAG by destroying the brand colour. It also emitted
 * `destructive: #E7000B`, a red, into an identity that bans red outright.
 *
 * 03-DESIGN-BLUEPRINT.md §1 anticipates exactly this and prescribes the remedy:
 * "If it cannot reach the brand colour, add a semantic token pair — the
 * sanctioned mechanism — defining the value explicitly... Adding a token pair is
 * normal work. Hand-editing generated colour values is not." Nothing in the
 * generated theme.ts is edited; these are explicit pairs beside it.
 *
 * ⚠ THE AUTOMATED CONTRAST AUDIT DOES NOT CHECK THESE.
 * `contrast-audit.mjs` reads a fixed pair list out of theme.ts. Every ratio below
 * was measured by hand with the same WCAG engine (tools/lib/wcag.mjs, truncated
 * never rounded) and is recorded in DESIGN-CONTRACT.md §6. If a value here
 * changes, re-measure it — no gate will catch you.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * DARK ONLY. The app is locked to dark (app.json userInterfaceStyle: "dark").
 * BRAND.md calls the bulb-on-matte-black the canonical logo state, and dark is
 * the web's default mode. There is deliberately no light palette here: a second
 * scheme nobody verifies is worse than one scheme that is right.
 */

// ── ratified scales, verbatim from docs/BRAND.md §4 (do not invent members) ──
const ember = {
  200: "#FEF08A",
  300: "#FDE047",
  400: "#FACC15", // brand primary — the bulb
  500: "#EAB308",
  600: "#CA8A04",
  700: "#A16207",
  800: "#854D0E", // burnt amber — the brand's error hue. No red exists here.
};

const ink = {
  50: "#FAFAFA",
  100: "#F4F4F5",
  200: "#E4E4E7",
  300: "#D4D4D8",
  400: "#A1A1AA",
  500: "#71717A",
  600: "#52525B",
  700: "#3F3F46",
  800: "#27272A",
  900: "#18181B",
  950: "#09090B", // matte black — the field
};

/**
 * Semantic colours. Ratio in each comment is measured against the surface named,
 * truncated not rounded (4.499 fails 4.5).
 *
 * Three roles DEVIATE from docs/BRAND.md on measured accessibility grounds. Each
 * deviation stays inside the ratified ember/ink scales — no new colour is
 * introduced and no red appears. All three are recorded in DESIGN-CONTRACT.md §12.
 */
const colors = {
  background: ink[950], // the field
  foreground: ink[50], // 19.06 on background — AAA
  surface: ink[900], // cards, rows
  "surface-foreground": ink[50], // 16.97 on surface — AAA
  "surface-raised": ink[800], // raised panels, pressed rows

  // DEVIATION 1 — BRAND.md §4.2 assigns ink-500 as "text-muted (both modes)".
  // Measured on matte black it is 4.11 and on the raised surface 3.66 — both
  // FAIL 4.5. ink-400 clears with room on both.
  "muted-foreground": ink[400], // 7.76 on background · 6.91 on surface — AA

  primary: ember[400], // the bulb
  // BRAND.md §7: white on ember measures 1.46 and fails. The web fixes this with
  // a CSS cascade rule; there is no cascade on device, so it is pinned here.
  "primary-foreground": ink[950], // 12.99 on primary — AAA
  "primary-pressed": ember[500], // press feedback: a lightness step, not a hue swap

  // DEVIATION 2 — BRAND.md §4.3 mandates ember-800 for error/danger. As TEXT on
  // matte black it measures 2.9 and fails badly (ember-700 also fails at 4.04).
  // ember-600 is the first shade that clears. ember-800 keeps its brand role as
  // an error FILL, where ink-50 on it measures 6.56 and passes.
  destructive: ember[600], // 6.77 on background — AA (error text)
  "destructive-fill": ember[800], // error surfaces/badges
  "destructive-fill-foreground": ink[50], // 6.56 on destructive-fill — AA

  success: ember[300], // 15.09 on background — AAA. Mono-amber: success is not green.

  // DEVIATION 3 — BRAND.md §5 maps the dark border to ink-800. At 1.33 against
  // the base that is fine for a DECORATIVE divider (WCAG 1.4.11 covers component
  // boundaries you must identify, not plain rules) but fails 3:1 for a control
  // outline. Two tokens, so the distinction cannot be lost at a call site.
  border: ink[800], // 1.33 — dividers ONLY, never a control boundary
  "border-control": ink[500], // 4.11 on background — inputs, toggles, anything identifiable

  ring: ember[400], // 12.99 on background — focus. Also the brand's glow signature.
};

/** 4dp base grid. Every spacing value in the app comes from here. */
const space = { 1: 4, 2: 8, 3: 12, 4: 16, 5: 24, 6: 32, 7: 48, 8: 64, 9: 96, 10: 128 };

/**
 * Mirrors the generated theme.ts exactly (1.25 major third from a 16dp base) so
 * the two never disagree. If DESIGN-CONTRACT.md's scaleRatio or radius changes,
 * regenerate theme.ts and re-sync these — recorded in the contract as a
 * re-apply item.
 */
const fontSize = {
  xs: 12, sm: 14, base: 16, lg: 18, xl: 20,
  "2xl": 25, "3xl": 31, "4xl": 39, "5xl": 49, "6xl": 61, "7xl": 76,
};

const radius = { sm: 7, md: 10, lg: 12, xl: 17, "2xl": 22, "3xl": 26, "4xl": 31 };

/**
 * Family keys are deliberately NOT named after Tailwind's font-weight utilities
 * (font-medium, font-semibold, font-bold, font-black are weights, not families —
 * reusing those names collides and the family silently loses). React Native has
 * no synthetic bolding across separate font files, so each weight is its own
 * family and is selected explicitly: font-body, font-emphasis, font-strong,
 * font-heading, font-wordmark.
 */
const fontFamily = {
  body: ["Inter_400Regular"],
  emphasis: ["Inter_500Medium"],
  strong: ["Inter_600SemiBold"],
  heading: ["Inter_700Bold"],
  wordmark: ["Inter_900Black"], // ELOSTATE wordmark — BRAND.md §2
};

module.exports = { ember, ink, colors, space, fontSize, radius, fontFamily };
